begin
match (n) optional match (n)-[r]-() delete n,r;

create (_0:`User` {`name`:"Adolf Torphy"})
create (_1:`User` {`name`:"Dr. Colton Beatty IV"})
create (_2:`User` {`name`:"Quinten Spencer"})
create (_3:`User` {`name`:"Charley Daugherty"})
create (_4:`User` {`name`:"Prof. Nella Pouros"})
create (_5:`User` {`name`:"Clare Weimann Jr."})
create (_6:`User` {`name`:"Okey Treutel"})
create (_7:`User` {`name`:"Dr. Percy Koepp"})
create (_8:`User` {`name`:"Mrs. Dannie Emard DVM"})
create (_9:`User` {`name`:"Jarrett Wolff"})
create (_10:`User` {`name`:"Dr. Deanna Bartell"})
create (_11:`User` {`name`:"Vickie Schaden DVM"})
create (_12:`User` {`name`:"Dr. Julio Runolfsdottir DVM"})
create (_13:`User` {`name`:"Reyna Thiel"})
create (_14:`User` {`name`:"Tyreek Langosh"})
create (_15:`User` {`name`:"Schuyler Terry"})
create (_16:`User` {`name`:"Cortney Crist"})
create (_17:`User` {`name`:"Dr. Montana Kub I"})
create (_18:`User` {`name`:"Dr. Gust Daniel"})
create (_19:`User` {`name`:"Prof. Amari Cremin II"})
create (_20:`User` {`name`:"Mr. Brock Krajcik PhD"})
create (_21:`User` {`name`:"Dr. Floy Kuhn I"})
create (_22:`User` {`name`:"Ms. Kristin Lind Sr."})
create (_23:`User` {`name`:"Randall Larkin II"})
create (_24:`User` {`name`:"Prof. Emmet Johns III"})
create (_25:`User` {`name`:"Miss Mabel Schmidt"})
create (_26:`User` {`name`:"Humberto Schroeder"})
create (_27:`User` {`name`:"Jonatan Rolfson"})
create (_28:`User` {`name`:"Abner Gutkowski"})
create (_29:`User` {`name`:"Dr. Benedict Hagenes IV"})
create (_30:`User` {`name`:"Zakary Padberg"})
create (_31:`User` {`name`:"Michale Lang"})
create (_32:`User` {`name`:"Hal Fay"})
create (_33:`User` {`name`:"Luz Weber"})
create (_34:`User` {`name`:"Mercedes Bechtelar"})
create (_35:`User` {`name`:"Mr. Ronaldo Dare"})
create (_36:`User` {`name`:"Bryce McGlynn"})
create (_37:`User` {`name`:"Mrs. Audreanne Stamm Sr."})
create (_38:`User` {`name`:"Isabel Hills"})
create (_39:`User` {`name`:"Mrs. Glenna Gislason DDS"})
create (_40:`User` {`name`:"Ernie Thiel"})
create (_41:`User` {`name`:"Miss Lillian Crona PhD"})
create (_42:`User` {`name`:"Amparo Ullrich"})
create (_43:`User` {`name`:"Ricardo Stamm"})
create (_44:`User` {`name`:"Stephon Kling"})
create (_45:`User` {`name`:"Lea Farrell"})
create (_46:`User` {`name`:"Jules Langosh DVM"})
create (_47:`User` {`name`:"Mr. Sean Schowalter III"})
create (_48:`User` {`name`:"Jessika Gaylord"})
create (_49:`User` {`name`:"Emmanuelle Effertz"})
create (_50:`User` {`name`:"Mr. Tracey Blick DVM"})
create (_51:`User` {`name`:"Daphnee Boehm"})
create (_52:`User` {`name`:"Laila Wyman"})
create (_53:`User` {`name`:"Finn Crooks"})
create (_54:`User` {`name`:"Dr. Ronny Heller"})
create (_55:`User` {`name`:"Prof. Anissa Lubowitz Sr."})
create (_56:`User` {`name`:"Prof. Melisa Rowe"})
create (_57:`User` {`name`:"Isom Heaney"})
create (_58:`User` {`name`:"Dr. Janiya Lesch"})
create (_59:`User` {`name`:"Antonetta Johnston II"})
create (_60:`User` {`name`:"Mrs. Madilyn Gleason II"})
create (_61:`User` {`name`:"Miracle Murphy"})
create (_62:`User` {`name`:"Dr. Bailey Heidenreich MD"})
create (_63:`User` {`name`:"Roosevelt Rath"})
create (_64:`User` {`name`:"Mr. Elwyn Osinski III"})
create (_65:`User` {`name`:"Suzanne Cormier Sr."})
create (_66:`User` {`name`:"Chesley Pouros"})
create (_67:`User` {`name`:"Leanne Pfannerstill"})
create (_68:`User` {`name`:"Rafaela Hilpert DVM"})
create (_69:`User` {`name`:"Autumn Zemlak"})
create (_70:`User` {`name`:"Rita Rogahn"})
create (_71:`User` {`name`:"Carolyne Volkman"})
create (_72:`User` {`name`:"Mallie Raynor"})
create (_73:`User` {`name`:"Kameron Renner"})
create (_74:`User` {`name`:"Bertram Roob"})
create (_75:`User` {`name`:"Dr. Grady Dach"})
create (_76:`User` {`name`:"Korbin Kutch"})
create (_77:`User` {`name`:"Leif Mante"})
create (_78:`User` {`name`:"Brennon Mills"})
create (_79:`User` {`name`:"Janae Kozey"})
create (_80:`User` {`name`:"Hardy Glover PhD"})
create (_81:`User` {`name`:"Mr. Cristian Mante"})
create (_82:`User` {`name`:"Dr. Demond Hodkiewicz"})
create (_83:`User` {`name`:"Prof. Jevon Reichel"})
create (_84:`User` {`name`:"Remington Carter"})
create (_85:`User` {`name`:"Michele Blanda"})
create (_86:`User` {`name`:"Myriam Lebsack"})
create (_87:`User` {`name`:"Katheryn Jenkins"})
create (_88:`User` {`name`:"Joanny Gerlach"})
create (_89:`User` {`name`:"Cassandra Larkin"})
create (_90:`User` {`name`:"Miss Jennie Krajcik Sr."})
create (_91:`User` {`name`:"Alessandro Skiles Jr."})
create (_92:`User` {`name`:"Julianne Jaskolski"})
create (_93:`User` {`name`:"Serena Abbott"})
create (_94:`User` {`name`:"Miss Stefanie Purdy"})
create (_95:`User` {`name`:"Vivien Sawayn"})
create (_96:`User` {`name`:"Prof. Mariane Smith Sr."})
create (_97:`User` {`name`:"Isom Wisozk I"})
create (_98:`User` {`name`:"Prof. Pierre Gusikowski DDS"})
create (_99:`User` {`name`:"Miss Shanel Mayert"})
create _0-[:`FRIENDSHIP`]->_1
create _0-[:`FRIENDSHIP`]->_2
create _0-[:`FRIENDSHIP`]->_3
create _0-[:`FRIENDSHIP`]->_5
create _0-[:`FRIENDSHIP`]->_9
create _1-[:`FRIENDSHIP`]->_2
create _1-[:`FRIENDSHIP`]->_3
create _1-[:`FRIENDSHIP`]->_5
create _1-[:`FRIENDSHIP`]->_9
create _2-[:`FRIENDSHIP`]->_3
create _2-[:`FRIENDSHIP`]->_5
create _2-[:`FRIENDSHIP`]->_8
create _2-[:`FRIENDSHIP`]->_12
create _3-[:`FRIENDSHIP`]->_4
create _3-[:`FRIENDSHIP`]->_5
create _3-[:`FRIENDSHIP`]->_11
create _3-[:`FRIENDSHIP`]->_12
create _3-[:`FRIENDSHIP`]->_13
create _4-[:`FRIENDSHIP`]->_9
create _5-[:`FRIENDSHIP`]->_6
create _5-[:`FRIENDSHIP`]->_12
create _5-[:`FRIENDSHIP`]->_13
create _6-[:`FRIENDSHIP`]->_14
create _6-[:`FRIENDSHIP`]->_16
create _7-[:`FRIENDSHIP`]->_8
create _7-[:`FRIENDSHIP`]->_13
create _7-[:`FRIENDSHIP`]->_14
create _8-[:`FRIENDSHIP`]->_14
create _8-[:`FRIENDSHIP`]->_15
create _8-[:`FRIENDSHIP`]->_16
create _9-[:`FRIENDSHIP`]->_13
create _9-[:`FRIENDSHIP`]->_15
create _10-[:`FRIENDSHIP`]->_15
create _10-[:`FRIENDSHIP`]->_19
create _11-[:`FRIENDSHIP`]->_12
create _11-[:`FRIENDSHIP`]->_15
create _11-[:`FRIENDSHIP`]->_17
create _11-[:`FRIENDSHIP`]->_19
create _12-[:`FRIENDSHIP`]->_13
create _12-[:`FRIENDSHIP`]->_15
create _13-[:`FRIENDSHIP`]->_16
create _13-[:`FRIENDSHIP`]->_17
create _13-[:`FRIENDSHIP`]->_23
create _14-[:`FRIENDSHIP`]->_16
create _15-[:`FRIENDSHIP`]->_16
create _15-[:`FRIENDSHIP`]->_17
create _15-[:`FRIENDSHIP`]->_23
create _15-[:`FRIENDSHIP`]->_24
create _16-[:`FRIENDSHIP`]->_21
create _16-[:`FRIENDSHIP`]->_24
create _16-[:`FRIENDSHIP`]->_26
create _17-[:`FRIENDSHIP`]->_23
create _17-[:`FRIENDSHIP`]->_27
create _18-[:`FRIENDSHIP`]->_25
create _19-[:`FRIENDSHIP`]->_23
create _19-[:`FRIENDSHIP`]->_24
create _19-[:`FRIENDSHIP`]->_26
create _19-[:`FRIENDSHIP`]->_27
create _21-[:`FRIENDSHIP`]->_22
create _21-[:`FRIENDSHIP`]->_23
create _21-[:`FRIENDSHIP`]->_27
create _21-[:`FRIENDSHIP`]->_28
create _21-[:`FRIENDSHIP`]->_30
create _22-[:`FRIENDSHIP`]->_31
create _23-[:`FRIENDSHIP`]->_26
create _24-[:`FRIENDSHIP`]->_25
create _24-[:`FRIENDSHIP`]->_26
create _24-[:`FRIENDSHIP`]->_27
create _24-[:`FRIENDSHIP`]->_29
create _24-[:`FRIENDSHIP`]->_31
create _24-[:`FRIENDSHIP`]->_34
create _25-[:`FRIENDSHIP`]->_28
create _26-[:`FRIENDSHIP`]->_27
create _26-[:`FRIENDSHIP`]->_35
create _27-[:`FRIENDSHIP`]->_34
create _27-[:`FRIENDSHIP`]->_35
create _28-[:`FRIENDSHIP`]->_30
create _28-[:`FRIENDSHIP`]->_35
create _29-[:`FRIENDSHIP`]->_33
create _30-[:`FRIENDSHIP`]->_34
create _30-[:`FRIENDSHIP`]->_36
create _31-[:`FRIENDSHIP`]->_32
create _31-[:`FRIENDSHIP`]->_34
create _31-[:`FRIENDSHIP`]->_36
create _32-[:`FRIENDSHIP`]->_34
create _32-[:`FRIENDSHIP`]->_36
create _32-[:`FRIENDSHIP`]->_41
create _33-[:`FRIENDSHIP`]->_35
create _33-[:`FRIENDSHIP`]->_36
create _34-[:`FRIENDSHIP`]->_35
create _34-[:`FRIENDSHIP`]->_41
create _34-[:`FRIENDSHIP`]->_42
create _35-[:`FRIENDSHIP`]->_36
create _35-[:`FRIENDSHIP`]->_41
create _36-[:`FRIENDSHIP`]->_44
create _37-[:`FRIENDSHIP`]->_39
create _37-[:`FRIENDSHIP`]->_44
create _37-[:`FRIENDSHIP`]->_45
create _38-[:`FRIENDSHIP`]->_42
create _38-[:`FRIENDSHIP`]->_44
create _38-[:`FRIENDSHIP`]->_45
create _38-[:`FRIENDSHIP`]->_46
create _39-[:`FRIENDSHIP`]->_47
create _40-[:`FRIENDSHIP`]->_41
create _40-[:`FRIENDSHIP`]->_45
create _41-[:`FRIENDSHIP`]->_42
create _41-[:`FRIENDSHIP`]->_49
create _42-[:`FRIENDSHIP`]->_45
create _42-[:`FRIENDSHIP`]->_46
create _42-[:`FRIENDSHIP`]->_52
create _44-[:`FRIENDSHIP`]->_45
create _45-[:`FRIENDSHIP`]->_51
create _46-[:`FRIENDSHIP`]->_51
create _47-[:`FRIENDSHIP`]->_51
create _47-[:`FRIENDSHIP`]->_54
create _48-[:`FRIENDSHIP`]->_53
create _48-[:`FRIENDSHIP`]->_55
create _50-[:`FRIENDSHIP`]->_55
create _52-[:`FRIENDSHIP`]->_53
create _52-[:`FRIENDSHIP`]->_55
create _52-[:`FRIENDSHIP`]->_61
create _53-[:`FRIENDSHIP`]->_55
create _53-[:`FRIENDSHIP`]->_61
create _53-[:`FRIENDSHIP`]->_63
create _54-[:`FRIENDSHIP`]->_57
create _54-[:`FRIENDSHIP`]->_61
create _54-[:`FRIENDSHIP`]->_62
create _55-[:`FRIENDSHIP`]->_57
create _55-[:`FRIENDSHIP`]->_59
create _56-[:`FRIENDSHIP`]->_61
create _56-[:`FRIENDSHIP`]->_62
create _57-[:`FRIENDSHIP`]->_59
create _57-[:`FRIENDSHIP`]->_63
create _58-[:`FRIENDSHIP`]->_59
create _58-[:`FRIENDSHIP`]->_66
create _58-[:`FRIENDSHIP`]->_67
create _59-[:`FRIENDSHIP`]->_61
create _59-[:`FRIENDSHIP`]->_62
create _60-[:`FRIENDSHIP`]->_62
create _60-[:`FRIENDSHIP`]->_63
create _60-[:`FRIENDSHIP`]->_65
create _60-[:`FRIENDSHIP`]->_70
create _61-[:`FRIENDSHIP`]->_62
create _61-[:`FRIENDSHIP`]->_64
create _61-[:`FRIENDSHIP`]->_67
create _61-[:`FRIENDSHIP`]->_70
create _62-[:`FRIENDSHIP`]->_65
create _63-[:`FRIENDSHIP`]->_65
create _63-[:`FRIENDSHIP`]->_66
create _63-[:`FRIENDSHIP`]->_73
create _64-[:`FRIENDSHIP`]->_70
create _64-[:`FRIENDSHIP`]->_71
create _64-[:`FRIENDSHIP`]->_72
create _64-[:`FRIENDSHIP`]->_74
create _65-[:`FRIENDSHIP`]->_66
create _65-[:`FRIENDSHIP`]->_67
create _65-[:`FRIENDSHIP`]->_71
create _66-[:`FRIENDSHIP`]->_67
create _66-[:`FRIENDSHIP`]->_70
create _66-[:`FRIENDSHIP`]->_74
create _67-[:`FRIENDSHIP`]->_74
create _68-[:`FRIENDSHIP`]->_70
create _68-[:`FRIENDSHIP`]->_71
create _68-[:`FRIENDSHIP`]->_76
create _68-[:`FRIENDSHIP`]->_77
create _68-[:`FRIENDSHIP`]->_78
create _69-[:`FRIENDSHIP`]->_74
create _70-[:`FRIENDSHIP`]->_71
create _70-[:`FRIENDSHIP`]->_75
create _70-[:`FRIENDSHIP`]->_76
create _70-[:`FRIENDSHIP`]->_78
create _71-[:`FRIENDSHIP`]->_72
create _71-[:`FRIENDSHIP`]->_73
create _71-[:`FRIENDSHIP`]->_76
create _71-[:`FRIENDSHIP`]->_78
create _72-[:`FRIENDSHIP`]->_75
create _72-[:`FRIENDSHIP`]->_76
create _72-[:`FRIENDSHIP`]->_80
create _73-[:`FRIENDSHIP`]->_76
create _73-[:`FRIENDSHIP`]->_80
create _73-[:`FRIENDSHIP`]->_83
create _76-[:`FRIENDSHIP`]->_80
create _76-[:`FRIENDSHIP`]->_86
create _77-[:`FRIENDSHIP`]->_79
create _77-[:`FRIENDSHIP`]->_82
create _78-[:`FRIENDSHIP`]->_81
create _79-[:`FRIENDSHIP`]->_85
create _79-[:`FRIENDSHIP`]->_89
create _80-[:`FRIENDSHIP`]->_82
create _80-[:`FRIENDSHIP`]->_86
create _80-[:`FRIENDSHIP`]->_90
create _81-[:`FRIENDSHIP`]->_86
create _81-[:`FRIENDSHIP`]->_89
create _82-[:`FRIENDSHIP`]->_86
create _82-[:`FRIENDSHIP`]->_89
create _83-[:`FRIENDSHIP`]->_90
create _84-[:`FRIENDSHIP`]->_94
create _85-[:`FRIENDSHIP`]->_86
create _86-[:`FRIENDSHIP`]->_90
create _86-[:`FRIENDSHIP`]->_96
create _87-[:`FRIENDSHIP`]->_89
create _87-[:`FRIENDSHIP`]->_91
create _87-[:`FRIENDSHIP`]->_92
create _87-[:`FRIENDSHIP`]->_94
create _87-[:`FRIENDSHIP`]->_96
create _88-[:`FRIENDSHIP`]->_89
create _88-[:`FRIENDSHIP`]->_91
create _88-[:`FRIENDSHIP`]->_94
create _89-[:`FRIENDSHIP`]->_90
create _89-[:`FRIENDSHIP`]->_94
create _89-[:`FRIENDSHIP`]->_96
create _89-[:`FRIENDSHIP`]->_99
create _90-[:`FRIENDSHIP`]->_91
create _91-[:`FRIENDSHIP`]->_98
create _92-[:`FRIENDSHIP`]->_97
create _93-[:`FRIENDSHIP`]->_94
create _93-[:`FRIENDSHIP`]->_95
create _93-[:`FRIENDSHIP`]->_98
create _94-[:`FRIENDSHIP`]->_95
create _94-[:`FRIENDSHIP`]->_98
create _95-[:`FRIENDSHIP`]->_97
create _96-[:`FRIENDSHIP`]->_98
;
commit
